### ISSUE TITLE
System.ArgumentException: oldValue is the empty string.

### ISSUE THREAD

**Issue by Sibren** [rille111/HomeAssistant.AppStarter#2]
I had success logging in, and now I'm trying so subscribe to something.
With this code:
    `public class SwitchUpdate : IHassApp
    {
        public async Task ExecuteAsync(EventData e, string rawData)
        {
            var a = "b";
            return;
        }

        public bool IsExecuting { get; set; }
        public string TriggeredByEntities { get; set; } = "light.*";
    }`

I get the following error:
FATAL UNHANDLED EXCEPTION: System.ArgumentException: oldValue is the empty string.

I also have a similar IHassApp-implementation, triggered by sun.sun, which gives me the same error.
I'm using Xamarin, but I don't think it has anything to do with this?
I'm using Home Assistant 0.75.1.

**Comment by Sibren** [comment]
I've now updated to the latest Home Assistant version, hoping this would fix it, but 0.76.1 now gives me:
'Unhandled Exception:

System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length occurred'

**Comment by Sibren** [comment]
Never mind. I'm stupid. :-D

**Comment by rille111** [comment]
Hello friend!

Was the issue fixed? I could add you as a contributor to the repo if you
wanna fix something? 🙂
