### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fma965** [rille111/HomeAssistant.AppStarter#3]
Hi. 

Your code looks perfect for my project however....

I would like to use this to just send services via websocket to Home Assistant, could you provide some code sample on how to do this, i thought i understood but it never seems to output anything other than 
![image](https://user-images.githubusercontent.com/1707290/55513178-03f75980-565d-11e9-98cb-08ed3beff1d1.png)

Thanks.

**Comment by ghost** [comment]
Have a look at the authorization flow for HomeAssistant and meet the requirements. There might be some changes to the code needed. If you open a PR i will merge it. Cheers!

**Comment by rille111** [comment]
> Have a look at the authorization flow for HomeAssistant and meet the requirements. There might be some changes to the code needed. If you open a PR i will merge it. Cheers!
